on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Just
              uses: extractions/setup-just@v3

            - name: Zip Extension
              run: |
                just zip-extension
            

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                repository: skullbite/gnome-add-to-steam
                token: ${{ secrets.ATS_TOKEN }}
                files: gnome-add-to-steam@pupper.space.zip
         